### ISSUE TITLE
Should there be a way to adjust the style of inlay hints in the README?

### ISSUE THREAD

**Issue by thep0y** [sublimelsp/LSP-rust-analyzer#56]
The default style of inlay hints may not be suitable for everyone.
It may be convenient to add custom css styles in `LSP-rust-analyzer.sublime-settings` to solve this issue.

---
Inlay hints in default style:
![截图_选择区域_20220203125542](https://user-images.githubusercontent.com/51874567/152283709-9745b388-aa5e-478a-8d0b-172dafd6d36c.png)

Inlay hints after adjusting the style:
![截图_选择区域_20220203125307](https://user-images.githubusercontent.com/51874567/152283765-625d3a6c-6c5d-49ea-a36f-30d038e672e0.png)

The css code I use:
```css
    body {{
        padding: 0;
        margin: 0 -1.4em -2.2em -1.2em;
        border: 0;
        font-size: 0.8em;
        position: relative;
        top: -0.82rem;
        line-height: 0.8em;
    }}
```
